apiVersion: v1
kind: Pod
metadata:
  name: gpu-cuda
spec:
  containers:
    - name: cuda-container
      image: reg.harbor.org/ngc/nvcr.io/nvidia/cuda:9.0-cudnn7.1-devel-ubuntu16.04
      command: [ "/bin/bash", "-c", "sleep 2147483647", "-c", "nvidia-smi" ]
      resources:
        limits:
          nvidia.com/gpu: 1
  imagePullSecrets:
  - name: harbor-admin
